language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t ashwani1218/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ashwani1218/Docker-React npm run test
