language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t ashwani1218/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ashwani1218/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "React-Docker"
  env: "ReactDocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-334800766908"
  bucket_path: "React-Docker"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_ACCESS_SECRET"
